In [24]:
def is_prime(number):
    for i in range(2, number):
        if number % i == 0:
            return False
    return True

In [31]:
def sum_primes(number):
    sum_of_primes = 0
    for i in range(2, number):
        if is_prime(i):
            sum_of_primes += i
    return sum_of_primes

In [32]:
sum_primes(2000)

277050

In [48]:
my_list = [1, 3, 5, True, False, 'something']

In [34]:
for item in my_list:
    print(item)

1
3
5
True
False
something


In [35]:
my_list[0]

1

In [36]:
my_list = iter(my_list)
type(my_list)

list_iterator

In [43]:
next(my_list)

StopIteration: 

In [45]:
for item in my_list:
    print(item)

1
3
5
True
False
something


In [49]:
my_list = iter(my_list)
iterating = True

while iterating:
    try:
        item = next(my_list)
    except StopIteration:
        iterating = False
    
    print(item)

1
3
5
True
False
something
something


In [50]:
import numpy as np

a = np.arange(20)

In [53]:
a = a.reshape(5, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [58]:
a.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [64]:
a[:4, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [65]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [71]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Jonat\OneDrive\General Assembly\Data-Science\Machine Learning Bootcamp\Data\titanic.csv')

In [70]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [72]:
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], dtype=object)

In [78]:
df.shape

(891, 12)

In [74]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [77]:
df.mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [82]:
np.mean(df)

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [94]:
df[['Name', 'Age', 'Fare']].sum()

Name    Braund, Mr. Owen HarrisCumings, Mrs. John Brad...
Age                                               21205.2
Fare                                              28693.9
dtype: object

In [100]:
df.iloc[2:7, ::2]

PassengerId  Pclass     Sex  SibSp            Ticket Cabin
2            3       3  female      0  STON/O2. 3101282   NaN
3            4       1  female      1            113803  C123
4            5       3    male      0            373450   NaN
5            6       3    male      0            330877   NaN
6            7       1    male      0             17463   E46

In [98]:
a[:4, 2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [101]:
df['Age'].mean()

29.69911764705882

In [102]:
df.Age.mean()

29.69911764705882

In [104]:
df[['Fare', 'SibSp']][:100].median()

Fare     15.675
SibSp     0.000
dtype: float64

In [107]:
df.iloc[:, -4:].mode()

Ticket  Fare        Cabin Embarked
0      1601  8.05      B96 B98        S
1    347082   NaN  C23 C25 C27      NaN
2  CA. 2343   NaN           G6      NaN

In [108]:
df.iloc[:250, :3].mean()

PassengerId    125.500
Survived         0.344
Pclass           2.416
dtype: float64

In [121]:
df[df.Age > 25]['Survived'][:100]

1      1
2      1
3      1
4      0
6      0
8      1
11     1
13     0
15     1
18     0
20     0
21     1
23     1
25     1
30     0
33     0
34     0
35     0
40     0
41     0
52     1
53     1
54     0
57     0
61     1
62     0
66     1
69     0
70     0
73     0
      ..
169    0
170    0
174    0
177    0
178    0
179    0
187    1
188    0
189    0
190    1
194    1
195    1
197    0
200    0
202    0
203    0
206    0
207    1
209    1
211    1
213    0
215    1
216    1
217    0
218    1
219    0
221    0
222    0
224    1
230    1
Name: Survived, Length: 100, dtype: int64

In [114]:
df['Pclass'].mean()

2.308641975308642

In [127]:
df = df.Age > 25

0      False
1       True
2       True
3       True
4       True
5      False
6       True
7      False
8       True
9      False
10     False
11      True
12     False
13      True
14     False
15      True
16     False
17     False
18      True
19     False
20      True
21      True
22     False
23      True
24     False
25      True
26     False
27     False
28     False
29     False
       ...  
861    False
862     True
863    False
864    False
865     True
866     True
867     True
868    False
869    False
870     True
871     True
872     True
873     True
874     True
875    False
876    False
877    False
878    False
879     True
880    False
881     True
882    False
883     True
884    False
885     True
886     True
887    False
888    False
889     True
890     True
Name: Age, Length: 891, dtype: bool

In [139]:
df[df.Sex == 'female']['Survived'].mean()

0.7420382165605095

In [150]:
print(str(df[(df.Pclass == 1) | (df.Pclass == 2)]['Survived'].mean() * 100) + '%')

55.75%


In [151]:
df[(df.Sex == 'female') & (df.SibSp >= 1)]['Survived'].mean()

0.6857142857142857

In [152]:
df['Age']**2 

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
5         NaN
6      2916.0
7         4.0
8       729.0
9       196.0
10       16.0
11     3364.0
12      400.0
13     1521.0
14      196.0
15     3025.0
16        4.0
17        NaN
18      961.0
19        NaN
20     1225.0
21     1156.0
22      225.0
23      784.0
24       64.0
25     1444.0
26        NaN
27      361.0
28        NaN
29        NaN
        ...  
861     441.0
862    2304.0
863       NaN
864     576.0
865    1764.0
866     729.0
867     961.0
868       NaN
869      16.0
870     676.0
871    2209.0
872    1089.0
873    2209.0
874     784.0
875     225.0
876     400.0
877     361.0
878       NaN
879    3136.0
880     625.0
881    1089.0
882     484.0
883     784.0
884     625.0
885    1521.0
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: Age, Length: 891, dtype: float64

In [153]:
df['New_Column'] = df['Age']**2

In [154]:
df['New_Column']

0       484.0
1      1444.0
2       676.0
3      1225.0
4      1225.0
5         NaN
6      2916.0
7         4.0
8       729.0
9       196.0
10       16.0
11     3364.0
12      400.0
13     1521.0
14      196.0
15     3025.0
16        4.0
17        NaN
18      961.0
19        NaN
20     1225.0
21     1156.0
22      225.0
23      784.0
24       64.0
25     1444.0
26        NaN
27      361.0
28        NaN
29        NaN
        ...  
861     441.0
862    2304.0
863       NaN
864     576.0
865    1764.0
866     729.0
867     961.0
868       NaN
869      16.0
870     676.0
871    2209.0
872    1089.0
873    2209.0
874     784.0
875     225.0
876     400.0
877     361.0
878       NaN
879    3136.0
880     625.0
881    1089.0
882     484.0
883     784.0
884     625.0
885    1521.0
886     729.0
887     361.0
888       NaN
889     676.0
890    1024.0
Name: New_Column, Length: 891, dtype: float64

In [156]:
columns = df.columns.tolist()

In [157]:
columns

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked',
 'New_Column']

In [158]:
columns = ['PassengerId',
 'Survived',
 'Pclass',
 'New_Column',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked',]

In [159]:
df = df[columns]

In [160]:
df.head()

PassengerId  Survived  Pclass  New_Column  \
0            1         0       3       484.0   
1            2         1       1      1444.0   
2            3         1       3       676.0   
3            4         1       1      1225.0   
4            5         0       3      1225.0   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [162]:
df.drop(['Age'], inplace=True, axis=1)

C:\Users\Jonat\Anaconda\lib\site-packages\pandas\core\frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)
